providers = ['node']
buildImage = 'ghcr.io/railwayapp/nixpacks:ubuntu-1707782610'

[variables]
CI = 'true'
NIXPACKS_METADATA = 'node'
NODE_ENV = 'production'
NPM_CONFIG_PRODUCTION = 'false'
NIXPACKS_NX_APP_NAME = 'api'

[phases.build]
dependsOn = ['install']
cmds = ['npm install --legacy-peer-deps', 'npm run postinstall', 'npm run prisma:migrate:prod']
cacheDirectories = ['node_modules/.cache']

[phases.install]
dependsOn = ['setup']
cmds = ['npm ci']
cacheDirectories = [
    '/root/.cache/Cypress',
    '/root/.npm',
]
paths = ['/app/node_modules/.bin']

[phases.setup]
nixPkgs = [
    'nodejs_18',
    'npm-6_x',
    'openssl',
    'python311'
]
nixLibs = [
  'libuuid',
  'libGL',
]
aptPkgs = ['build-essential']

nixOverlays = ['https://github.com/railwayapp/nix-npm-overlay/archive/main.tar.gz']
nixpkgsArchive = 'bf744fe90419885eefced41b3e5ae442d732712d'

[start]
cmd = 'npm start api'

