import { NgModule } from '@angular/core';
import {
  RemixIconModule,
  RiBookmarkFill,
  RiBookmarkLine,
  RiChat1Line,
  RiChatPollLine,
  RiClipboardLine,
  RiCloseLine,
  RiCodeLine,
  RiCompass3Line,
  RiFullscreenExitFill,
  RiFullscreenFill,
  RiGithubLine,
  RiHeart2Fill,
  RiHeart2Line,
  RiHome2Line,
  RiImageLine,
  RiMoreFill,
  RiNotification4Line,
  RiShareLine,
  RiStackLine,
  RiTerminalBoxLine,
  RiText,
  RiUser3Line,
} from 'angular-remix-icon';

@NgModule({
  imports: [
    RemixIconModule.configure({
      RiHome2Line,
      RiNotification4Line,
      RiBookmarkLine,
      RiBookmarkFill,
      RiUser3Line,
      RiCompass3Line,
      RiImageLine,
      RiCodeLine,
      RiTerminalBoxLine,
      RiStackLine,
      RiGithubLine,
      RiChatPollLine,
      RiHeart2Line,
      RiHeart2Fill,
      RiChat1Line,
      RiShareLine,
      RiFullscreenFill,
      RiFullscreenExitFill,
      RiText,
      RiClipboardLine,
      RiMoreFill,
      RiCloseLine,
    }),
  ],
  exports: [RemixIconModule],
})
export class IconModule {}
